// -----------------------------------------------------------------------------------------------------
// | <auto-generated>                                                                                  |
// |    This code was generated by a tool.                                                             |
// |                                                                                                   |
// |    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. |
// | </auto-generated>                                                                                 |
// -----------------------------------------------------------------------------------------------------

// Define JSON file path variable for easy adjustment

namespace PSXMaster;
public partial class NavigationPageMappings
{
    public static Dictionary<string, Type> PageDictionary { get; } = new Dictionary<string, Type>
    {
        {"PSXMaster.Views.HomeLandingPage", typeof(PSXMaster.Views.HomeLandingPage)},
        {"PSXMaster.Views.GameTransferPage", typeof(PSXMaster.Views.GameTransferPage)},
        {"PSXMaster.Views.QueueGamesPage", typeof(PSXMaster.Views.QueueGamesPage)},
        {"PSXMaster.Views.GameDetailsPage", typeof(PSXMaster.Views.GameDetailsPage)},
    };
}
